### ISSUE TITLE
Connection using WiFi

### ISSUE THREAD

**Issue by ManaliDubal** [KVRajil/RemoteDesktopSharing#1]
Can we connect through Wifi or only LAN?

**Comment by KVRajil** [comment]
Both

**Comment by ManaliDubal** [comment]
How to make it work with wifi ?

**Comment by KVRajil** [comment]
Connect your computers into a wifi network .Install server app on one system and client on others

**Comment by ManaliDubal** [comment]
Yes, I did that. And it worked like a charm! Thank you once again. One concern though:
Can we connect computers located at distance, means not in the same LAN or Wifi network? Like I want to use it for communicating between two offices in different states. Is it possible?

**Comment by KVRajil** [comment]
Yes possible . But you need a static IP . You need to buy it from your ISP

**Comment by ManaliDubal** [comment]
Thank you for your reply. So we need to buy static IP for both client and
server ? Or only client ?

**Comment by KVRajil** [comment]
for server

**Comment by ManaliDubal** [comment]
Okay. Thank you again.

**Comment by KVRajil** [comment]
welcome
